### PR TITLE
Simulate the break

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by massich** [comment]
here is what is left of OpenMEEG and contains the same code as in https://github.com/openmeeg/openmeeg/pull/313 Here it compiles and pass the tests, not in OpenMEEG.

cc:@agramfort

**Comment by agramfort** [comment]
good there is hope !

I would do now the other way around. Remove all code from openmeeg until you get to the amount of code you have here. At some point in the process it should go from not working to working

**Comment by massich** [comment]
That's what I did. The commit referenced in the commit have the same code
and Cmake structure.

**Comment by agramfort** [comment]
Same code works in one repo and fails in another ? Can it be ci caching ?

**Comment by massich** [comment]
my machine does the same. It has to be some of the extra things in the build system, but no idea what.

**Comment by agramfort** [comment]
tell me how to replicate
just get the 2 repos and branches and it should break in one?

**Comment by massich** [comment]
@agramfort yes. But take [this one](https://github.com/massich/openmeeg/tree/313_mimic-conda-forge_HEAD) since I'm pointing the PR's HEAD inito different places to check differences between my PC and travis.

**Comment by massich** [comment]
closing

**Pull request closed without merging**
